language: node_js # Node.js based project
node_js:
  - 12 # Level of Node.js to use
branches:
  only:
    - master
cache:
  directories:
  - node_modules # Cache the node_modules folder for quicker build times
script:
  - npm run deploy # Runs next build
  - touch out/.nojekyll # Creates a file telling Github not to build the project using Jekyll
deploy:
  provider: pages # Informs Travis this is a deployment to GitHub Pages
  skip_cleanup: true # Prevents Travis from resetting the working directory made during the build
  github_token: $github_token # GitHub access token to use when pushing to the gh-pages branch
  local_dir: out # Directory to push to the gh-pages branch
  on:
    branch: master # Only deploy when the build is on master branch
before_install:
  - wget https://raw.githubusercontent.com/rzfury/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh begin $WEBHOOK_URL
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL